theme: jekyll-theme-cayman
title: Text-CARD
description: The official examples of article "Temporal Calibrating and Distilling for Scene-Text Aware Text-Video Retrieval"
github:
  is_project_page: false
